//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Department
{
    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }
}

public partial class Employee
{
    public int EmployeeId { get; set; }
    public string EmployeeName { get; set; }
    public string Department { get; set; }
    public Nullable<System.DateTime> DateOfJoining { get; set; }
    public string PhotoFileName { get; set; }
}
